# Format of title for sending images.
# filename - Send title as filename.
# separate - Send title as message before image, send image with actual filename.
# inline   - Send title and image in same message, filename is sent in img title.
format: 'separate'
# The interval to poll CommitStrip for new comics in.
poll_interval: 900
# The time to sleep between send requests when broadcasting a new CommitStrip.
# Set to 0 to disable sleep or -1 to run all requests asynchronously at once.
spam_sleep: 10
# Whether or not to allow !commitstrip reindex.
# Disables itself after the command is used once.
allow_reindex: true
# Maximum number of search results
max_search_results: 10
# Base command without the prefix (!).
base_command: commitstrip
